
import React, { useState, useEffect } from 'react';
import { 
  TrendingUp, 
  BarChart3, 
  ShieldAlert, 
  Target, 
  Clock, 
  Zap, 
  ChevronDown, 
  AlertCircle,
  Loader2,
  RefreshCcw,
  Search,
  CheckCircle2,
  DollarSign,
  XCircle,
  TrendingDown,
  Info,
  Share2,
  Check
} from 'lucide-react';
import { analyzeTrade } from './gemini';
import { AnalysisInput, AnalysisResult, OrderBookStatus, TradeBookStatus } from './types';

const App: React.FC = () => {
  const [orderBook, setOrderBook] = useState<OrderBookStatus>('Netral');
  const [tradeBook, setTradeBook] = useState<TradeBookStatus>('Netral');
  const [brokerCodes, setBrokerCodes] = useState<string[]>(['', '', '']);
  const [stockCode, setStockCode] = useState('');
  const [currentPrice, setCurrentPrice] = useState<string>('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [copied, setCopied] = useState(false);

  const handleAnalyze = async () => {
    if (!brokerCodes[0] && !stockCode) return;
    setLoading(true);
    setResult(null); 
    try {
      const input: AnalysisInput = {
        orderBook,
        tradeBook,
        brokerCodes: brokerCodes.filter(c => c !== ''),
        stockCode: stockCode.toUpperCase(),
        currentPrice: currentPrice ? parseFloat(currentPrice) : undefined
      };
      const data = await analyzeTrade(input);
      setResult(data);
    } catch (error) {
      console.error(error);
    } finally {
      setLoading(false);
    }
  };

  const copyToClipboard = () => {
    if (!result) return;
    const text = `*VELARC QUANTUM ANALYSIS: ${stockCode.toUpperCase()}*\n\nSignal: ${result.signal} (${result.signalName})\n\nAnalisa: ${result.analysis}\n\nAction: ${result.action}\nTarget: ${result.target}\nStop Loss: ${result.cutLoss}\n\n_Generated by Velarc AI_`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const severityColors = {
    success: 'text-emerald-400 border-emerald-500/30 bg-emerald-500/5',
    warning: 'text-amber-400 border-amber-500/30 bg-amber-500/5',
    error: 'text-rose-400 border-rose-500/30 bg-rose-500/5',
    info: 'text-blue-400 border-blue-500/30 bg-blue-500/5',
  };

  const severityBg = {
    success: 'from-emerald-600/20 to-transparent border-emerald-500/50',
    warning: 'from-amber-600/20 to-transparent border-amber-500/50',
    error: 'from-rose-600/20 to-transparent border-rose-500/50',
    info: 'from-blue-600/20 to-transparent border-blue-500/50',
  };

  return (
    <div className="min-h-screen bg-[#030712] text-slate-100 font-sans selection:bg-blue-500/30 pb-12">
      {/* Background Decor */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none opacity-20">
        <div className="absolute top-[-10%] left-[-10%] w-[60%] h-[40%] bg-blue-600 blur-[140px] rounded-full" />
        <div className="absolute bottom-[-10%] right-[-10%] w-[60%] h-[40%] bg-purple-600 blur-[140px] rounded-full" />
      </div>

      <div className="relative max-w-5xl mx-auto px-4 md:px-6 py-8 md:py-12">
        {/* Header */}
        <header className="flex flex-row justify-between items-center gap-4 mb-8 md:mb-12">
          <div className="flex items-center gap-3 md:gap-4">
            <div className="p-2.5 bg-gradient-to-br from-blue-500 to-blue-700 rounded-xl shadow-lg shadow-blue-600/20">
              <Zap className="text-white fill-white" size={18} />
            </div>
            <div>
              <h1 className="text-xl md:text-2xl font-bold tracking-tight text-white flex items-center gap-2">
                Velarc Quantum <span className="text-blue-500 text-[10px] bg-blue-500/10 px-1.5 py-0.5 rounded border border-blue-500/20 font-black">PRO</span>
              </h1>
            </div>
          </div>
          
          <button 
            onClick={() => {
              setOrderBook('Netral');
              setTradeBook('Netral');
              setBrokerCodes(['', '', '']);
              setStockCode('');
              setCurrentPrice('');
              setResult(null);
            }}
            className="flex items-center justify-center p-2 bg-slate-900/50 border border-slate-800 rounded-lg hover:bg-slate-800 transition-all text-slate-500 hover:text-slate-300"
            title="Reset All"
          >
            <RefreshCcw size={14} />
          </button>
        </header>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 md:gap-8 items-start">
          {/* Input Panel */}
          <div className="lg:col-span-5 space-y-6">
            <div className="p-5 md:p-6 bg-slate-900/40 backdrop-blur-2xl border border-slate-800/50 rounded-[2rem] shadow-2xl space-y-6">
              <h2 className="text-[10px] font-black uppercase tracking-[0.2em] text-blue-500 flex items-center gap-2">
                <Info size={14} /> Market Data Feed
              </h2>
              
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <label className="text-[10px] font-bold text-slate-500 uppercase tracking-wider flex items-center gap-2">
                    <Search size={12} className="text-blue-500" /> Ticker
                  </label>
                  <input 
                    type="text"
                    maxLength={5}
                    value={stockCode}
                    onChange={(e) => setStockCode(e.target.value.toUpperCase())}
                    placeholder="BBCA"
                    className="w-full bg-slate-950 border border-slate-800/80 rounded-2xl px-4 py-4 text-white focus:outline-none focus:ring-2 focus:ring-blue-500/50 transition-all font-mono text-lg font-bold"
                  />
                </div>
                <div className="space-y-2">
                  <label className="text-[10px] font-bold text-slate-500 uppercase tracking-wider flex items-center gap-2">
                    <DollarSign size={12} className="text-emerald-500" /> Price
                  </label>
                  <input 
                    type="number"
                    value={currentPrice}
                    onChange={(e) => setCurrentPrice(e.target.value)}
                    placeholder="10250"
                    className="w-full bg-slate-950 border border-slate-800/80 rounded-2xl px-4 py-4 text-white focus:outline-none focus:ring-2 focus:ring-blue-500/50 transition-all font-mono text-lg font-bold"
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <label className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">Order Book</label>
                  <div className="relative">
                    <select 
                      value={orderBook}
                      onChange={(e) => setOrderBook(e.target.value as OrderBookStatus)}
                      className="w-full bg-slate-950 border border-slate-800/80 rounded-2xl px-4 py-4 text-white appearance-none focus:outline-none focus:ring-2 focus:ring-blue-500/50 transition-all font-bold text-sm"
                    >
                      <option value="Bid Dominan">Bid Dominan</option>
                      <option value="Ask Dominan">Ask Dominan</option>
                      <option value="Netral">Netral</option>
                    </select>
                    <ChevronDown size={16} className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-500 pointer-events-none" />
                  </div>
                </div>
                <div className="space-y-2">
                  <label className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">Trade Book</label>
                  <div className="relative">
                    <select 
                      value={tradeBook}
                      onChange={(e) => setTradeBook(e.target.value as TradeBookStatus)}
                      className="w-full bg-slate-950 border border-slate-800/80 rounded-2xl px-4 py-4 text-white appearance-none focus:outline-none focus:ring-2 focus:ring-blue-500/50 transition-all font-bold text-sm"
                    >
                      <option value="Buy Dominan">Buy Dominan</option>
                      <option value="Sell Dominan">Sell Dominan</option>
                      <option value="Netral">Netral</option>
                    </select>
                    <ChevronDown size={16} className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-500 pointer-events-none" />
                  </div>
                </div>
              </div>

              <div className="space-y-3">
                <label className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">Top Accumulator (Brokers)</label>
                <div className="grid grid-cols-3 gap-2">
                  {brokerCodes.map((code, idx) => (
                    <input 
                      key={idx}
                      type="text"
                      maxLength={2}
                      value={code}
                      onChange={(e) => {
                        const newCodes = [...brokerCodes];
                        newCodes[idx] = e.target.value.toUpperCase();
                        setBrokerCodes(newCodes);
                      }}
                      placeholder={`#${idx + 1}`}
                      className="w-full bg-slate-950 border border-slate-800/80 rounded-xl py-4 text-center text-white focus:outline-none focus:ring-2 focus:ring-blue-500/50 transition-all font-mono text-lg font-bold uppercase"
                    />
                  ))}
                </div>
              </div>

              <button 
                onClick={handleAnalyze}
                disabled={loading || (!brokerCodes[0] && !stockCode)}
                className="w-full py-5 bg-gradient-to-r from-blue-600 to-blue-500 hover:from-blue-500 hover:to-blue-400 disabled:opacity-50 disabled:cursor-not-allowed text-white font-black uppercase tracking-widest rounded-[1.5rem] shadow-2xl shadow-blue-600/30 transition-all flex items-center justify-center gap-3 group active:scale-[0.98]"
              >
                {loading ? (
                  <div className="flex items-center gap-3">
                    <Loader2 className="animate-spin" size={20} />
                    <span className="text-sm">Calculating Probability...</span>
                  </div>
                ) : (
                  <>
                    <span className="text-sm">Run Deep Reasoning</span>
                    <TrendingUp size={20} className="group-hover:translate-x-1 group-hover:-translate-y-1 transition-transform" />
                  </>
                )}
              </button>
            </div>
          </div>

          {/* Results Panel */}
          <div className="lg:col-span-7">
            {result ? (
              <div className={`rounded-[2.5rem] border p-1 shadow-2xl animate-in fade-in slide-in-from-bottom-8 duration-700 bg-gradient-to-b ${severityBg[result.severity]}`}>
                <div className="bg-slate-950/80 backdrop-blur-3xl rounded-[2.3rem] p-6 md:p-8 space-y-8 relative overflow-hidden">
                  {/* Copy Button */}
                  <button 
                    onClick={copyToClipboard}
                    className="absolute top-6 right-6 p-3 bg-slate-900/80 border border-slate-800 rounded-2xl text-slate-400 hover:text-white transition-all active:scale-90"
                  >
                    {copied ? <Check size={20} className="text-emerald-500" /> : <Share2 size={20} />}
                  </button>

                  {/* Decision Header */}
                  <div className="flex flex-col items-center md:items-start text-center md:text-left pt-4">
                    <div className="flex flex-col md:flex-row items-center gap-6">
                       <div className={`p-5 rounded-full border-4 ${result.signal === 'YA' ? 'bg-emerald-500/20 border-emerald-500/30 text-emerald-400' : 'bg-rose-500/20 border-rose-500/30 text-rose-400'}`}>
                         {result.signal === 'YA' ? <CheckCircle2 size={48} /> : <XCircle size={48} />}
                       </div>
                       <div>
                         <div className={`text-[10px] font-black uppercase tracking-[0.4em] mb-2 ${severityColors[result.severity]}`}>
                           Quantum Decision
                         </div>
                         <h3 className={`text-6xl md:text-7xl font-black italic tracking-tighter ${result.signal === 'YA' ? 'text-emerald-400' : 'text-rose-500'}`}>
                           {result.signal}
                         </h3>
                         <p className="text-slate-400 text-xs font-black mt-2 uppercase tracking-[0.2em]">{result.signalName}</p>
                       </div>
                    </div>
                  </div>

                  {/* Analysis Text */}
                  <div className="space-y-3 pt-6 border-t border-slate-800/50">
                    <h4 className="text-slate-500 text-[9px] font-black uppercase tracking-widest flex items-center gap-2">
                      <BarChart3 size={12} className="text-blue-500" /> Intelligence Report
                    </h4>
                    <p className="text-slate-100 leading-relaxed text-xl md:text-2xl font-semibold italic">
                      "{result.analysis}"
                    </p>
                  </div>

                  {/* Actions Grid */}
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="p-5 bg-slate-900/60 border border-slate-800/50 rounded-3xl">
                      <h4 className="text-slate-500 text-[9px] font-black uppercase tracking-widest mb-3 flex items-center gap-2">
                        {result.signal === 'YA' ? <TrendingUp size={12} className="text-emerald-500" /> : <TrendingDown size={12} className="text-rose-500" />} Strat Matrix
                      </h4>
                      <p className="text-white font-bold text-sm md:text-base">{result.action}</p>
                    </div>
                    <div className="p-5 bg-slate-900/60 border border-slate-800/50 rounded-3xl">
                      <h4 className="text-slate-500 text-[9px] font-black uppercase tracking-widest mb-3 flex items-center gap-2">
                        <Target size={12} className="text-blue-500" /> Target
                      </h4>
                      <p className={`font-black text-2xl md:text-3xl ${result.target === '-' ? 'text-slate-700' : 'text-emerald-400'}`}>{result.target}</p>
                    </div>
                    <div className="p-5 bg-slate-900/60 border border-slate-800/50 rounded-3xl">
                      <h4 className="text-slate-500 text-[9px] font-black uppercase tracking-widest mb-3 flex items-center gap-2">
                        <Clock size={12} className="text-purple-500" /> Horizon
                      </h4>
                      <p className={`font-bold ${result.timeframe === '-' ? 'text-slate-700' : 'text-white'}`}>{result.timeframe}</p>
                    </div>
                    <div className="p-5 bg-rose-500/5 border border-rose-500/20 rounded-3xl">
                      <h4 className="text-rose-400 text-[9px] font-black uppercase tracking-widest mb-3 flex items-center gap-2">
                        <ShieldAlert size={12} /> Stop Loss
                      </h4>
                      <p className={`font-black text-2xl md:text-3xl ${result.cutLoss === '-' ? 'text-slate-700' : 'text-rose-500'}`}>{result.cutLoss}</p>
                    </div>
                  </div>

                  {/* Warnings/Notes */}
                  <div className="p-5 bg-slate-900/80 border border-slate-800 rounded-3xl flex gap-4 items-start">
                    <AlertCircle className="text-blue-500 shrink-0 mt-1" size={18} />
                    <div>
                      <h5 className="text-slate-500 text-[9px] font-black uppercase tracking-widest mb-1">Quantum Feedback</h5>
                      <p className="text-slate-400 text-xs leading-relaxed font-medium">{result.notes}</p>
                    </div>
                  </div>
                </div>
              </div>
            ) : (
              <div className="h-full min-h-[400px] flex flex-col items-center justify-center p-8 md:p-12 bg-slate-900/20 border-2 border-dashed border-slate-800/50 rounded-[3rem] text-center space-y-6">
                <div className="p-8 bg-slate-900 rounded-full border border-slate-800 text-slate-700 animate-pulse">
                  <BarChart3 size={64} />
                </div>
                <div>
                  <h3 className="text-slate-400 font-black text-xl md:text-2xl uppercase tracking-tighter">System Awaiting Data</h3>
                  <p className="text-slate-600 max-w-xs mx-auto text-xs md:text-sm leading-relaxed mt-2 font-medium">
                    Velarc Quantum siap membedah manipulasi bandar. Masukkan data di panel kiri untuk memulai sinkronisasi intelijen.
                  </p>
                </div>
                <div className="flex gap-2">
                   {[1,2,3].map(i => <div key={i} className="w-1.5 h-1.5 rounded-full bg-slate-800" />)}
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Footer */}
        <footer className="mt-16 md:mt-24 pt-8 border-t border-slate-900/50 text-center flex flex-col items-center gap-2">
          <p className="text-slate-600 text-[9px] uppercase tracking-[0.3em] font-black flex items-center justify-center gap-3">
            <span className="w-8 h-[1px] bg-slate-900/30" />
            Quantum Engine v2.5 | Stable Build
            <span className="w-8 h-[1px] bg-slate-900/30" />
          </p>
          <p className="text-blue-500/40 text-[10px] font-black uppercase tracking-[0.6em] animate-pulse">
            Engineered by Alfian
          </p>
        </footer>
      </div>
    </div>
  );
};

export default App;
